In [1]:
import numpy as np

n1 = np.array([10,20,30,40])       #creating array using numerical python library
n1

array([10, 20, 30, 40])

In [2]:
type(n1)

numpy.ndarray

In [6]:
#initializing numpy arrays as zero
#zeros(no.of rows , no.of cols)
n1 = np.zeros((2,2))  
n1

array([[0., 0.],
       [0., 0.]])

In [7]:
#initializing nparray using same number
n1 = np.full((2,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10]])

In [9]:
#initializing numpy array within a range
n2 = np.arange(10,20)       #20 is exclusive
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
# with skip paramter
n2 = np.arange(10,40,5)
n2

array([10, 15, 20, 25, 30, 35])

In [12]:
#initializing nparray with random numbers
#from 1 to 100 range i want 5 random integers
n1 = np.random.randint(1,100,5)
n1

array([15, 54, 85, 35, 66])

In [16]:
#checking the shape of array
n1 = np.array([[10,20,30,40],[50,60,70,80]])
#telling 2 rows and 4 cols
n1.shape

(2, 4)

In [17]:
n1.shape = (4,2)
n1

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [18]:
#joining two nparrays
#1. vstack() - vertical stack 
n1 = np.array([10,20,3,4])
n2 = np.array([2,5,9,4])
np.vstack((n1,n2))

array([[10, 20,  3,  4],
       [ 2,  5,  9,  4]])

In [ ]:
#2.hstack()  
#3.column_stack()

In [19]:
n1 = np.array([10,20,3,4])
n2 = np.array([2,5,9,4])
np.intersect1d(n1,n2)

array([4])

In [20]:
n1 = np.array([10,20,3,4])
n2 = np.array([2,5,9,4])
np.setdiff1d(n1,n2)    #removes common and gives unique from n1 (n1-n2)

array([ 3, 10, 20])

In [21]:
n1 = np.array([10,20,3,4])
n2 = np.array([2,5,9,4])
np.setdiff1d(n2,n1)     #changing sequence

array([2, 5, 9])

In [22]:
#addition of numpy arrays
n1 = np.array([10,20,3,4])
n2 = np.array([2,5,9,4])
np.sum([n1,n2])

57

In [23]:
#addition of numpy arrays only column elements using axis = 0
n1 = np.array([10,20,3,4])
n2 = np.array([2,5,9,4])
np.sum([n1,n2],axis=0)

array([12, 25, 12,  8])

In [24]:
#addition of numpy arrays only row elements using axis = 1
n1 = np.array([10,20,3,4])
n2 = np.array([2,5,9,4])
np.sum([n1,n2],axis=1)

array([37, 20])

In [26]:
#aritematic operations
#adding 1 no. to each element
n1 = np.array([10,20,3,4])
n1=n1+1
n1

array([11, 21,  4,  5])

In [27]:
#numpy MATH functions
n1 = np.array([10,20,30,40])
np.mean(n1)

25.0

In [28]:
n1 = np.array([10,20,30,40])
np.std(n1)

11.180339887498949

In [29]:
n1 = np.array([10,20,30,40])
np.median(n1)

25.0